apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: bookinfo-request-auth
spec:
  selector:
    matchLabels:
      app: productpage
  jwtRules:
  - issuer: "http://localhost:8083/realms/Istio"
    jwksUri: "http://keycloak.default.svc.cluster.local/realms/Istio/protocol/openid-connect/certs"